version: "3.8"

services:
  # SonarQube
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    depends_on:
      - sonarqube-database  
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonarqube
      - SONARQUBE_JVM_OPTS=-Xmx2g -Xms2g
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - 9000:9000
    networks:
      - springify-net

  sonarqube-database:
    container_name: sonarqube-database
    image: postgres:12
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
    volumes:
      - sonarqube_database:/var/lib/postgresql
      - sonarqube_database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - springify-net




networks:
  springify-net:

volumes:
  sonarqube_database_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_database:
  sonarqube_extensions:
