spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

  application:
    name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/